apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticker-pulse-ai
  labels:
    app: ticker-pulse-ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ticker-pulse-ai
  template:
    metadata:
      labels:
        app: ticker-pulse-ai
    spec:
      containers:
        - name: ticker-pulse-ai
          image: ticker-pulse-ai:latest
          ports:
            - containerPort: 8081
          env:
            - name: VITE_SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ticker-pulse-secrets
                  key: supabase-url
            - name: VITE_SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: ticker-pulse-secrets
                  key: supabase-anon-key
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Secret
metadata:
  name: ticker-pulse-secrets
type: Opaque
stringData:
  supabase-url: "https://kbgkmqvceyjnrqdzrbnm.supabase.co"
  supabase-anon-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiZ2ttcXZjZXlqbnJxZHpyYm5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI0MDI4NDEsImV4cCI6MjA0Nzk3ODg0MX0.wEeO7wJKUi1JNrmNDWOFKG_I6WQAfkkzBdPGW4LnT9Y"
